document.body.innerHTML =
    document.body.innerHTML

    // idioms
    .replace(new RegExp("brings to light", "gi"), "reveals")
    .replace(new RegExp("half a century", "gi"), "fifty years")
    .replace(new RegExp("accounting for", "gi"), "explaining")
    .replace(new RegExp("for over", "gi"), "for more than")
    .replace(new RegExp("at hand", "gi"), "nearby")
    .replace(new RegExp("feel free to", "gi"), "you may")
    .replace(new RegExp("feel free", "gi"), "you may")
    .replace(new RegExp("a lot of", "gi"), "much")
    .replace(new RegExp("what about", "gi"), "consider")
    .replace(new RegExp("on account of", "gi"), "due to")
    .replace(new RegExp("deal with", "gi"), "handle")
    .replace(new RegExp("way more", "gi"), "much more")

    // simplify vocabulary
    .replace(new RegExp("realizing", "gi"), "seeing")
    .replace(new RegExp("itself", "gi"), "its self")
    .replace(new RegExp("infinitude", "gi"), "limitlessness")
    .replace(new RegExp("thereby", "gi"), "by that means")
    .replace(new RegExp("significance", "gi"), "meaning")
    .replace(new RegExp("consider", "gi"), "think carefully about")
    .replace(new RegExp("unable", "gi"), "not powerful enough")
    .replace(new RegExp(" able", "gi"), " powerful enough")
    .replace(new RegExp("significant", "gi"), "important")
    .replace(new RegExp("production", "gi"), "making")
    .replace(new RegExp("produce", "gi"), "make")
    .replace(new RegExp("improve", "gi"), "make better")
    .replace(new RegExp("generate", "gi"), "make")
    .replace(new RegExp("establish", "gi"), "make")
    .replace(new RegExp("construct", "gi"), "make")
    .replace(new RegExp("develop", "gi"), "make")
    .replace(new RegExp("imagine", "gi"), "think of")
    .replace(new RegExp("ability", "gi"), "power")
    .replace(new RegExp("abilities", "gi"), "powers")
    .replace(new RegExp("historical", "gi"), "old")
    .replace(new RegExp("determinant", "gi"), "cause")
    .replace(new RegExp("phenomenon", "gi"), "observation")
    .replace(new RegExp("ambiguity", "gi"), "uncertainty")
    .replace(new RegExp("ultimately", "gi"), "in the end")
    .replace(new RegExp("analysis", "gi"), "study")
    .replace(new RegExp("grounded", "gi"), "based")
    .replace(new RegExp("thereupon", "gi"), "immediately")
    .replace(new RegExp("immediate", "gi"), "present")
    .replace(new RegExp("proceeds", "gi"), "goes on")
    .replace(new RegExp("become", "gi"), "begin to be")
    .replace(new RegExp("likewise", "gi"), "also")
    .replace(new RegExp("concentrate", "gi"), "focus")
    .replace(new RegExp("nature", "gi"), "form")
    .replace(new RegExp("categories", "gi"), "forms")
    .replace(new RegExp("category", "gi"), "form")
    .replace(new RegExp("shape", "gi"), "form")
    .replace(new RegExp("type", "gi"), "form")
    .replace(new RegExp("structure", "gi"), "form")
    .replace(new RegExp("fundamental", "gi"), "basic")
    .replace(new RegExp("termed", "gi"), "called")
    .replace(new RegExp("prominent", "gi"), "prominent")
    .replace(new RegExp("albeit", "gi"), "although")
    .replace(new RegExp("doctrine", "gi"), "belief")
    .replace(new RegExp("entitled", "gi"), "called")
    .replace(new RegExp("partially", "gi"), "partly")
    .replace(new RegExp("employ", "gi"), "use")
    .replace(new RegExp("technique", "gi"), "way")
    .replace(new RegExp("manner", "gi"), "way")
    .replace(new RegExp("mode", "gi"), "way")
    .replace(new RegExp("means", "gi"), "way")
    .replace(new RegExp("result", "gi"), "effect")
    .replace(new RegExp("indeed", "gi"), "surely")
    .replace(new RegExp("safe", "gi"), "sure")
    .replace(new RegExp("bad", "gi"), "not good")
    .replace(new RegExp("great", "gi"), "good")
    .replace(new RegExp("excellent", "gi"), "good")
    .replace(new RegExp("splended", "gi"), "good")
    .replace(new RegExp("amazing", "gi"), "good")
    .replace(new RegExp("unless", "gi"), "except if")
    .replace(new RegExp("always", "gi"), "at all times")
    .replace(new RegExp("regard", "gi"), "think of")
    .replace(new RegExp("must", "gi"), "has to")
    .replace(new RegExp("independent", "gi"), "free")
    .replace(new RegExp("dependent", "gi"), "unfree")
    .replace(new RegExp("consequence", "gi"), "effect")
    .replace(new RegExp("provide", "gi"), "give")
    .replace(new RegExp("procedures", "gi"), "ways of doing")
    .replace(new RegExp("procedure", "gi"), "way of doing")
    .replace(new RegExp("process", "gi"), "way of doing")
    .replace(new RegExp("active", "gi"), "engaging")
    .replace(new RegExp("immersed", "gi"), "engaged")
    .replace(new RegExp("literally", "gi"), "exactly")
    .replace(new RegExp("explored", "gi"), "looked at")
    .replace(new RegExp("explore", "gi"), "look at")
    .replace(new RegExp("described", "gi"), "talked about")
    .replace(new RegExp("describes", "gi"), "talks about")
    .replace(new RegExp("describe", "gi"), "talk about")
    .replace(new RegExp("attempt", "gi"), "try")
    .replace(new RegExp("claim", "gi"), "say")
    .replace(new RegExp("studied", "gi"), "looked at")
    .replace(new RegExp("study", "gi"), "look at")
    .replace(new RegExp("seek", "gi"), "look for")
    .replace(new RegExp("seeking", "gi"), "looking for")
    .replace(new RegExp("propose", "gi"), "put forth")
    .replace(new RegExp("necessary", "gi"), "needed")
    .replace(new RegExp("required", "gi"), "needed")
    .replace(new RegExp("require", "gi"), "need")
    .replace(new RegExp("interpretation", "gi"), "understanding")
    .replace(new RegExp("recognise", "gi"), "understand")
    .replace(new RegExp("comprehend", "gi"), "grasp")
    .replace(new RegExp("understand", "gi"), "grasp")
    .replace(new RegExp("equivalent", "gi"), "equal")
    .replace(new RegExp("affix", "gi"), "stick")
    .replace(new RegExp("influential", "gi"), "powerful")
    .replace(new RegExp("within", "gi"), "inside")
    .replace(new RegExp("recognize", "gi"), "know again")
    .replace(new RegExp("already", "gi"), "before now")
    .replace(new RegExp("entire", "gi"), "whole")
    .replace(new RegExp("constituent", "gi"), "part")
    .replace(new RegExp("therefore", "gi"), "for that reason")
    .replace(new RegExp("portray", "gi"), "show")
    .replace(new RegExp("manifestation", "gi"), "showing")
    .replace(new RegExp("obvious", "gi"), "clear")
    .replace(new RegExp("manifest", "gi"), "clearly show")
    .replace(new RegExp("demonstrate", "gi"), "clearly show")
    .replace(new RegExp("sentiment", "gi"), "opinion")
    .replace(new RegExp("incline", "gi"), "dispose")
    .replace(new RegExp("corporeal", "gi"), "bodily")
    .replace(new RegExp("reveal", "gi"), "show")
    .replace(new RegExp("examining", "gi"), "looking at")
    .replace(new RegExp("examine", "gi"), "look at")
    .replace(new RegExp("adequate", "gi"), "okay")
    .replace(new RegExp("inadequacy", "gi"), "weakness")
    .replace(new RegExp("attend to", "gi"), "do something about")
    .replace(new RegExp("negotiate", "gi"), "agree about")
    .replace(new RegExp("generally", "gi"), "usually")
    .replace(new RegExp("extraordinary", "gi"), "unusual")
    .replace(new RegExp("usual", "gi"), "normal")
    .replace(new RegExp("common", "gi"), "normal")
    .replace(new RegExp("assumed", "gi"), "thought true")
    .replace(new RegExp("assume", "gi"), "think true")
    .replace(new RegExp("continually", "gi"), "regularly")
    .replace(new RegExp("impact", "gi"), "effect")
    .replace(new RegExp("before it", "gi"), "in front of it")

    // big words
    .replace(new RegExp("unitary", "gi"), "single")

    // contractions
    .replace(new RegExp("does not", "gi"), "doesn't")
    .replace(new RegExp("do not", "gi"), "don't")
    .replace(new RegExp("is not", "gi"), "isn't")
    .replace(new RegExp("was not", "gi"), "wasn't")
    .replace(new RegExp("i am", "gi"), "i'm")
    .replace(new RegExp("that is", "gi"), "that's")

    // reduce syllables (of largest word)
    .replace(new RegExp("only", "gi"), "just")
    .replace(new RegExp("primary", "gi"), "main")
    .replace(new RegExp("similar to", "gi"), "like")
    .replace(new RegExp("similar", "gi"), "like")
    .replace(new RegExp("situation", "gi"), "state")
    .replace(new RegExp("because", "gi"), "since")
    .replace(new RegExp("create", "gi"), "make") // this doesn't conjugate well
    .replace(new RegExp("according to", "gi"), "as stated by")
    .replace(new RegExp("appropriate", "gi"), "proper")
    .replace(new RegExp("intentionally", "gi"), "purposefully")
    .replace(new RegExp("separate", "gi"), "split")
    .replace(new RegExp("possess", "gi"), "have")
    .replace(new RegExp("purely", "gi"), "just")
    .replace(new RegExp("almost", "gi"), "not")
    .replace(new RegExp("probably", "gi"), "maybe")
    .replace(new RegExp("certain", "gi"), "sure")
    .replace(new RegExp("beforehand", "gi"), "in advance")
    .replace(new RegExp("altogether", "gi"), "completely")
    .replace(new RegExp("concerning", "gi"), "about")
    .replace(new RegExp("whenever", "gi"), "any time")
    .replace(new RegExp("desire", "gi"), "want")
    .replace(new RegExp("desirable", "gi"), "wanted")
    .replace(new RegExp("difficult", "gi"), "hard")
    .replace(new RegExp("regular", "gi"), "normal")
    .replace(new RegExp("decisive", "gi"), "definite")
    .replace(new RegExp("abstract", "gi"), "ideal")
    .replace(new RegExp("upset", "gi"), "sad")
    .replace(new RegExp("despite", "gi"), "in spite of")
    .replace(new RegExp("a few", "gi"), "some")
    .replace(new RegExp("not true", "gi"), "false")
    .replace(new RegExp("every", "gi"), "each")
    .replace(new RegExp("have to", "gi"), "must")
    // .replace(new RegExp("different", "gi"), "unlike")


    // Compound words
    .replace(new RegExp("anything", "gi"), "any thing")
    .replace(new RegExp("nothing", "gi"), "no thing")
    .replace(new RegExp("none", "gi"), "no one")
    .replace(new RegExp("anyone", "gi"), "any one")
    .replace(new RegExp("something", "gi"), "some thing")
    .replace(new RegExp("cannot", "gi"), "can not")
    .replace(new RegExp("someone", "gi"), "some one")
    .replace(new RegExp("sometimes", "gi"), "some times")

    // pointless
    .replace(new RegExp("oh", "gi"), "")
    .replace(new RegExp("please", "gi"), "")
    .replace(new RegExp("however", "gi"), "")
    .replace(new RegExp(" very ", "gi"), " ")
    .replace(new RegExp("quite", "gi"), "")
    .replace(new RegExp("really", "gi"), "")
    .replace(new RegExp("actually", "gi"), "")
    .replace(new RegExp("in fact", "gi"), "")
    .replace(new RegExp("much", "gi"), "")
    .replace(new RegExp("a bit of", "gi"), "")
    .replace(new RegExp("sure,", "gi"), "")
    .replace(new RegExp("i'm just saying that", "gi"), "")
    .replace(new RegExp("god knows", "gi"), "")
    .replace(new RegExp("highly", "gi"), "")
    .replace(new RegExp(" just ", "gi"), " ")

    // intensives

    ;
