document.body.innerHTML =
    document.body.innerHTML

    // idioms
    .replace(new RegExp("brings to light", "gi"), "reveals")
    .replace(new RegExp("accounting for", "gi"), "explaining")
    .replace(new RegExp("for over", "gi"), "for more than")
    .replace(new RegExp("at hand", "gi"), "nearby")
    .replace(new RegExp("feel free to", "gi"), "you may")
    .replace(new RegExp("feel free", "gi"), "you may")
    .replace(new RegExp("a lot of", "gi"), "much")
    .replace(new RegExp("what about", "gi"), "consider")
    .replace(new RegExp("on account of", "gi"), "due to")
    .replace(new RegExp("way more", "gi"), "much more")

    // simplify vocabulary
    .replace(new RegExp("unable", "gi"), "not powerful enough")
    .replace(new RegExp("able", "gi"), "powerful enough")
    .replace(new RegExp("imagine", "gi"), "think of")
    .replace(new RegExp("ability", "gi"), "power")
    .replace(new RegExp("nature", "gi"), "essence")
    .replace(new RegExp("abilities", "gi"), "powers")
    .replace(new RegExp("develop", "gi"), "build")
    .replace(new RegExp("determinant", "gi"), "cause")
    .replace(new RegExp("phenomenon", "gi"), "observation")
    .replace(new RegExp("ambiguity", "gi"), "uncertainty")
    .replace(new RegExp("ultimately", "gi"), "in the end")
    .replace(new RegExp("analysis", "gi"), "study")
    .replace(new RegExp("grounded", "gi"), "based")
    .replace(new RegExp("immediate", "gi"), "present")
    .replace(new RegExp("concentrate", "gi"), "focus")
    .replace(new RegExp("shape", "gi"), "form")
    .replace(new RegExp("type", "gi"), "form")
    .replace(new RegExp("structure", "gi"), "form")
    .replace(new RegExp("fundamental", "gi"), "basic")
    .replace(new RegExp("doctrine", "gi"), "belief")
    .replace(new RegExp("means", "gi"), "way")
    .replace(new RegExp("result", "gi"), "effect")
    .replace(new RegExp("indeed", "gi"), "surely")
    .replace(new RegExp("safe", "gi"), "sure")
    .replace(new RegExp("bad", "gi"), "not good")
    .replace(new RegExp("great", "gi"), "good")
    .replace(new RegExp("excellent", "gi"), "good")
    .replace(new RegExp("splended", "gi"), "good")
    .replace(new RegExp("amazing", "gi"), "good")
    .replace(new RegExp("unless", "gi"), "except if")
    .replace(new RegExp("always", "gi"), "at all times")
    .replace(new RegExp("consequence", "gi"), "effect")
    .replace(new RegExp("provide", "gi"), "give")
    .replace(new RegExp("procedures", "gi"), "ways of doing")
    .replace(new RegExp("procedure", "gi"), "way of doing")
    .replace(new RegExp("active", "gi"), "engaging")
    .replace(new RegExp("immersed", "gi"), "engaged")
    .replace(new RegExp("literally", "gi"), "exactly")
    .replace(new RegExp("seek", "gi"), "look for")
    .replace(new RegExp("seeking", "gi"), "looking for")
    .replace(new RegExp("propose", "gi"), "put forth")
    .replace(new RegExp("necessary", "gi"), "needed")
    .replace(new RegExp("required", "gi"), "needed")
    .replace(new RegExp("require", "gi"), "need")
    .replace(new RegExp("interpretation", "gi"), "understanding")
    .replace(new RegExp("recognise", "gi"), "understand")
    .replace(new RegExp("understand", "gi"), "grasp")
    .replace(new RegExp("influential", "gi"), "powerful")
    .replace(new RegExp("within", "gi"), "inside")
    .replace(new RegExp("recognize", "gi"), "know again")
    .replace(new RegExp("constituent", "gi"), "part")
    .replace(new RegExp("therefore", "gi"), "for that reason")
    .replace(new RegExp("portray", "gi"), "show")
    .replace(new RegExp("manifestation", "gi"), "showing")
    .replace(new RegExp("manifest", "gi"), "clearly show")
    .replace(new RegExp("corporeal", "gi"), "bodily")
    .replace(new RegExp("reveal", "gi"), "show")
    .replace(new RegExp("examining", "gi"), "looking at")
    .replace(new RegExp("examine", "gi"), "look at")
    .replace(new RegExp("adequate", "gi"), "okay")
    .replace(new RegExp("inadequacy", "gi"), "weakness")
    .replace(new RegExp("attend to", "gi"), "do something about")
    .replace(new RegExp("extraordinary", "gi"), "unusual")
    .replace(new RegExp("demonstrate", "gi"), "clearly show")
    .replace(new RegExp("continually", "gi"), "regularly")

    // big words
    .replace(new RegExp("unitary", "gi"), "single")

    // contractions
    .replace(new RegExp("do not", "gi"), "don't")
    .replace(new RegExp("is not", "gi"), "isn't")
    .replace(new RegExp("was not", "gi"), "wasn't")
    .replace(new RegExp("i am", "gi"), "i'm")
    .replace(new RegExp("that is", "gi"), "that's")

    // reduce syllables (of largest word)
    .replace(new RegExp("only", "gi"), "just")
    .replace(new RegExp("primary", "gi"), "main")
    .replace(new RegExp("similar to", "gi"), "like")
    .replace(new RegExp("similar", "gi"), "like")
    .replace(new RegExp("situation", "gi"), "state")
    .replace(new RegExp("because", "gi"), "since")
    .replace(new RegExp("create", "gi"), "make") // this doesn't conjugate well
    .replace(new RegExp("according to", "gi"), "as stated by")
    .replace(new RegExp("appropriate", "gi"), "proper")
    .replace(new RegExp("intentionally", "gi"), "purposefully")
    .replace(new RegExp("separate", "gi"), "split")
    .replace(new RegExp("possess", "gi"), "have")
    .replace(new RegExp("purely", "gi"), "just")
    .replace(new RegExp("almost", "gi"), "not")
    .replace(new RegExp("probably", "gi"), "maybe")
    .replace(new RegExp("certain", "gi"), "sure")
    .replace(new RegExp("beforehand", "gi"), "in advance")
    .replace(new RegExp("altogether", "gi"), "completely")
    .replace(new RegExp("concerning", "gi"), "about")
    .replace(new RegExp("whenever", "gi"), "any time")
    .replace(new RegExp("desire", "gi"), "want")
    .replace(new RegExp("desirable", "gi"), "wanted")
    .replace(new RegExp("difficult", "gi"), "hard")
    .replace(new RegExp("regular", "gi"), "normal")
    .replace(new RegExp("decisive", "gi"), "definite")
    .replace(new RegExp("abstract", "gi"), "ideal")
    .replace(new RegExp("upset", "gi"), "sad")
    .replace(new RegExp("despite", "gi"), "in spite of")
    .replace(new RegExp("a few", "gi"), "some")
    .replace(new RegExp("not true", "gi"), "false")
    .replace(new RegExp("every", "gi"), "each")
    .replace(new RegExp("have to", "gi"), "must")
    // .replace(new RegExp("different", "gi"), "unlike")


    // Compound words
    .replace(new RegExp("nothing", "gi"), "no thing")
    .replace(new RegExp("anyone", "gi"), "any one")
    .replace(new RegExp("something", "gi"), "some thing")
    .replace(new RegExp("cannot", "gi"), "can not")
    .replace(new RegExp("someone", "gi"), "some one")

    // pointless
    .replace(new RegExp("oh", "gi"), "")
    .replace(new RegExp("please", "gi"), "")
    .replace(new RegExp("however", "gi"), "")
    .replace(new RegExp(" very ", "gi"), " ")
    .replace(new RegExp("quite", "gi"), "")
    .replace(new RegExp("really", "gi"), "")
    .replace(new RegExp("actually", "gi"), "")
    .replace(new RegExp("in fact", "gi"), "")
    .replace(new RegExp("much", "gi"), "")
    .replace(new RegExp("a bit of", "gi"), "")
    .replace(new RegExp("sure,", "gi"), "")
    .replace(new RegExp("i'm just saying that", "gi"), "")
    .replace(new RegExp("god knows", "gi"), "")
    .replace(new RegExp("highly", "gi"), "")
    .replace(new RegExp(" just ", "gi"), " ")

    // intensives

    ;
